import os
import tkinter as tk
from tkinter import messagebox, Canvas
from tkinter import ttk
import cv2
from PIL import Image, ImageTk
import connect
import random
import csv
import pandas as pd
import recognize
import markAttendance
import pymysql.cursors
import autogeneratedEmail
LARGEFONT = ("Verdana", 35)
MEDIUMFONT = ("Verdana", 20)
teachers = {
    'hussein': ['1234', 'benzenephenol369@gmail.com'],
    'nayan': ['4321', 'n.mandliya@somaiya.edu'],
    'sneha': ['0000', 'sneha.kothi@somaiya.edu'],
}
currentLecture = ['', '']
currentTeacher = ['0', '']

def checkCSV(self,controller,dict1, yearInput, subjectInput):
     flag = True
     flag1=True
     fileName = dict1[0] + '_' + dict1[1]
     print(fileName)
     if(len(fileName)==1):
         tk.messagebox.showerror('No lecture scheduled', 'Lecture is not scheduled!!!')
         flag1=False
     if(flag1==True):
         if not markAttendance.checkDatabase():
             tk.messagebox.showwarning('No Students', 'Attendance Not Taken Yet!!!')
         else:
             dbcon = pymysql.connect(host="localhost", user="root", password="Nayan@123", database="attendance")
             try:
                 SQL_Query = pd.read_sql_query(
                     "select * from tempAtt", dbcon)
                 df = pd.DataFrame(SQL_Query)
                 print(df)
                 dbcon.close()

                 # deleting CSV
                 file = f'AttendanceCSV/{fileName}.csv'
                 if (os.path.exists(file) and os.path.isfile(file)):
                     os.remove(file)
                     print("file deleted")
                 else:
                     print("file not found")

                 # creating new CSV
                 df.to_csv(file)
                 yearInput.delete(0, 'end')
                 subjectInput.delete(0, 'end')
                 autogeneratedEmail.send_email('Attendance', f'For {fileName[0]} year, subject {fileName[2:]}', fileName, currentTeacher[1])
                 currentTeacher[0] = "0"
                 currentTeacher[1] = ""
             except:
                 print("Error")
             print("Mail CSV")

# Teacher Login Page
def verifyTeacher(controller, userName, password):
    print(userName.get())
    print(password.get())
    user = False

    for teacher in teachers.keys():
        if teacher == userName.get():
            if(currentTeacher[0]=="0" or currentTeacher[0]==userName.get()):
                if teachers[userName.get()][0] == password.get():
                    currentTeacher[0] = userName.get()
                    currentTeacher[1] = teachers[userName.get()][1]
                    print("Correct")
                    userName.delete(0, 'end')
                    password.delete(0, 'end')
                    return controller.show_frame(selectSubject)
                else:
                    print("wrong password")
                    user = True
                    userName.delete(0, 'end')
                    password.delete(0, 'end')
                    tk.messagebox.showwarning('Incorrect Password', 'Wrong Password please try again')
                    break
            else:
                tk.messagebox.showwarning('Lecture Scheduled', f'{currentLecture[1]} Lecture already scheduled')
                userName.delete(0, 'end')
                password.delete(0, 'end')
                return controller.show_frame(StartPage)
    if not user:
        print('wrong username')
        userName.delete(0, 'end')
        password.delete(0, 'end')
        tk.messagebox.showwarning('Incorrect username', 'Wrong username please try again')
        # third window frame registerPage


def showCreateMessage(controller, yearInput, subjectInput):
    tk.messagebox.showinfo('Class Created', 'Attendance will be marked in csv')
    currentLecture[0] = yearInput.get()
    currentLecture[1] = subjectInput.get()
    print(currentLecture)
    df = pd.DataFrame(list())
    df.to_csv(f'AttendanceCSV/{currentLecture[0]}_{currentLecture[1]}.csv')
    return currentLecture, controller.show_frame(StartPage)


class tkinterApp(tk.Tk):

    # __init__ function for class tkinterApp
    def __init__(self, *args, **kwargs):
        # __init__ function for class Tk
        tk.Tk.__init__(self, *args, **kwargs)

        # creating a container
        self.geometry('800x550')
        self.title('Attendance Portal')
        container = tk.Frame(self)
        container.pack(side="top", fill="both", expand=True)

        container.grid_rowconfigure(0, weight=1)
        container.grid_columnconfigure(0, weight=1)

        # initializing frames to an empty array
        self.frames = {}

        # iterating through a tuple consisting
        # of the different page layouts
        for F in (StartPage, loginPage, registerPage, selectSubject):
            frame = F(container, self)

            # initializing frame of that object from
            # startpage, loginPage, registerPage respectively with
            # for loop
            self.frames[F] = frame

            frame.grid(row=0, column=0, sticky="nsew")

        self.show_frame(StartPage)

    # to display the current frame passed as
    # parameter
    def show_frame(self, cont):
        frame = self.frames[cont]
        frame.tkraise()

# first window frame startpage
class StartPage(tk.Frame):
    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent, bg='#accdf5')

        # label of frame Layout 2
        label = tk.Label(self, text="SMART ATTENDANCE SYSTEM", font=LARGEFONT, bg='#accdf5')

        # putting the grid in its place by using
        # grid
        label.grid(row=0, column=2, padx=35, pady=10, rowspan=2)
        login = tk.Button(self, text='Login', command=lambda: controller.show_frame(loginPage), bg='#4e74fc', font=MEDIUMFONT)
        register = tk.Button(self, text='Register', command=lambda: controller.show_frame(registerPage), bg='#4e74fc', font=MEDIUMFONT)
        markAttendance = tk.Button(self, text='Mark Attendance', command=lambda: recognize.recognizeStudent(currentTeacher),
                                   bg='#4e74fc', font=MEDIUMFONT)

        login.grid(row=2, column=2, padx=10, pady=10)
        register.grid(row=3, column=2, padx=10, pady=10)
        markAttendance.grid(row=4, column=2, padx=10, pady=10)

class selectSubject(tk.Frame):
    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent, bg='#accdf5')

        # label of frame Layout 2
        label = tk.Label(self, text="Select Subject", font=LARGEFONT, bg='#accdf5')

        # putting the grid in its place by using
        # grid
        # label.grid(row=0, column=4, padx=10, pady=10)
        label.place(x=210, y=10)

        year = tk.Label(self, text="Year", font=("Verdana", 16), bg='#accdf5')
        year.place(x=250, y=100)
        # year.grid(row=2, column=1, pady=10)
        yearInput = tk.Entry(self, width=12, borderwidth=6, font=("Verdana", 14))
        yearInput.place(x=385, y=100)
        yearInput.focus()
        # yearInput.grid(row=2, column=2, pady=10, padx=10)

        subject = tk.Label(self, text="Subject", font=("Verdana", 16), bg='#accdf5')
        subject.place(x=240, y=175)
        # subject.grid(row=3, column=1, pady=10)
        subjectInput = tk.Entry(self, width=12, borderwidth=6, font=("Verdana", 14))
        subjectInput.place(x=385, y=170)
        # subjectInput.grid(row=3, column=2, pady=10, padx=10)

        back = tk.Button(self, text='back',font=("Verdana", 15), command=lambda: controller.show_frame(StartPage), bg='#4e74fc')
        # back.grid(row=4, column=2, pady=10)
        back.place(x=210, y=280)

        create = tk.Button(self, text='Create',font=("Verdana", 15), command=lambda: showCreateMessage(controller, yearInput, subjectInput), bg='#4e74fc')
        # create.grid(row=4, column=4, pady=10)
        create.place(x=520, y=280)

        send = tk.Button(self,text='Send Attendance',font=("Verdana", 15), command=lambda: checkCSV(self,controller,currentLecture, yearInput, subjectInput), bg='#4e74fc')
        send.grid(row=5, column=1, pady=10)
        send.place(x=305, y=280)

class loginPage(tk.Frame):

    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent, bg='#accdf5')
        label = tk.Label(self, text="LOGIN PAGE", font=LARGEFONT, bg='#accdf5')
        # label.grid(row=0, column=4, padx=10, pady=10)
        label.place(x=240, y=10)

        tname = tk.Label(self, text="Name", bg='#accdf5', font=("Verdana", 16))
        # tname.grid(row=1, column=4, pady=10)
        tname.place(x=250, y=100)

        userName = tk.Entry(self, width=12, borderwidth=6, font=("Verdana", 14))
        # userName.grid(row=2, column=4, padx=10, pady=10)
        userName.place(x=385, y=100)
        userName.focus()

        pas = tk.Label(self, text="Password", bg='#accdf5', font=("Verdana", 16))
        # pas.grid(row=3, column=4, pady=10)
        pas.place(x=245, y=175)

        password = tk.Entry(self, width=12, borderwidth=6, font=("Verdana", 14))
        # password.grid(row=4, column=4, padx=10, pady=10)
        password.place(x=385, y=170)

        back = tk.Button(self, text="Back",font=MEDIUMFONT,
                          command=lambda: controller.show_frame(StartPage), bg='#4e74fc')

        # back.grid(row=5, column=2, padx=10, pady=50)
        back.place(x=200, y=280)

        submit = tk.Button(self, text="submit",font=MEDIUMFONT,
                            command=lambda: verifyTeacher(controller, userName, password), bg='#4e74fc')

        # submit.grid(row=5, column=5, padx=10, pady=50)
        submit.place(x=500, y=280)

class registerPage(tk.Frame):
    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent, bg='#accdf5')
        label = tk.Label(self, text="Student Registration", font=LARGEFONT, bg='#accdf5')
        # label.grid(row=0, column=4, padx=10, pady=10)
        label.place(x=150, y=10)

        fName = tk.Label(self, text="First Name", bg='#accdf5', font=("Verdana", 16))
        # fName.grid(row=2, column=1, pady=10)
        fName.place(x=230, y=100)

        studentFName = tk.Entry(self, width=12, borderwidth=6, font=("Verdana", 14))
        # studentFName.grid(row=2, column=2, padx=10, pady=10)
        studentFName.place(x=375, y=100)
        studentFName.focus()

        lName = tk.Label(self, text="Last Name", bg='#accdf5', font=("Verdana", 16))
        # lName.grid(row=3, column=1, pady=10)
        lName.place(x=235,y=175)

        studentLName = tk.Entry(self, width=12, borderwidth=6, font=("Verdana", 14))
        # studentLName.grid(row=3, column=2, padx=10, pady=10)
        studentLName.place(x=375,y=170)

        roll = tk.Label(self, text="Roll Number", bg='#accdf5', font=("Verdana", 16))
        # roll.grid(row=4, column=1, pady=10)
        roll.place(x=220,y=250)

        roll_no = tk.Entry(self, width=12, borderwidth=6, font=("Verdana", 14))
        # roll_no.grid(row=4, column=2, padx=10, pady=10)
        roll_no.place(x=375,y=245)

        back = tk.Button(self, text="Back", font=MEDIUMFONT,
                          command=lambda: controller.show_frame(StartPage), bg='#4e74fc')
        # back.grid(row=1, column=1, padx=10, pady=10)
        back.place(x=200,y=325)

        submit = tk.Button(self, text="submit", font=MEDIUMFONT,
                            command=lambda: connect.insert(studentFName, studentLName, roll_no, random.randint(0,100), studentFName.get(), studentLName.get(), roll_no.get()), bg='#4e74fc')
        # submit.grid(row=5, column=1, padx=10, pady=10)
        submit.place(x=500,y=325)


app = tkinterApp()
app.mainloop()
